### ISSUE TITLE
Compile error using VS 2022 (Windows 11) due to hash_compare (+ solution)

### ISSUE THREAD

**Issue by GZouw** [vegastrike/Vega-Strike-Engine-Source#827]
Hi,

I had a compile error with Visual Studio 2022  (Windows 11), following the instructions in readme.md. The error is:
 error C2039: 'hash_compare': is not a member of 'std'

 I traced the issue back to 
[https://developercommunity.visualstudio.com/t/stdext::hash_compare-has-been-removed-in/10182319](https://developercommunity.visualstudio.com/t/stdext::hash_compare-has-been-removed-in/10182319)

The issue can be fixed by adding 
-D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS

as a compiler flag according to the link above. 

After doing this, compilation was successfull. 

I do not know I solved this the proper way, but I hope this helps.

BR

Gerbrand

**Comment by BenjamenMeyer** [comment]
@GZouw thank for filing an issue. `hash_compare` is a method we add - see https://github.com/vegastrike/Vega-Strike-Engine-Source/blob/master/engine/src/gnuhash.h#L76.

What version are you compiling so we can be sure it gets fixed. Thanks!

**Comment by GZouw** [comment]
> What version are you compiling so we can be sure it gets fixed. Thanks!

I was compiling v0.8.0 (which I thought was the stable release).

**Comment by BenjamenMeyer** [comment]
@GZouw yes, it is the current stable release; we're working on getting 0.9.x out the door. Thanks.

NOTE: it should be finding our built-in hash_compare method still - see https://github.com/vegastrike/Vega-Strike-Engine-Source/blob/0.8.x/engine/src/gnuhash.h#L81C7-L81C19.

Will take a look.

**Comment by BenjamenMeyer** [comment]
0.8.x is now outside our support cycle as we just released 0.9.x which includes Windows native builds directly from our CI.
So this should no longer be an issue and we should be fixing these kinds of things pretty quickly when they do happen going forward.  Please feel free to re-open if this does continue with 0.9.x and newer.
