### ISSUE TITLE
Sunrise not working properly

### ISSUE THREAD

**Issue by royfalk** [vegastrike/Vega-Strike-Engine-Source#1024]
When orbiting Atlantis in 0.8, sunrise has a yellow/orange tint to it.
This is now gone.

**Comment by evertvorster** [comment]
Thanks for putting this up here. I checked the latest commit from 0.8.x, and it was gone there too. 
I'm literally hunting this sunset now, just to have a screenshot. There is nothing on Google. :(

**Comment by royfalk** [comment]
To be clear, it is in 0.8.0. You can stop now. I have my brackets and know what I'm looking for. I'm pretty sure I even know what caused it. I'll get to it tomorrow probably.

**Comment by royfalk** [comment]
Based on testing, this is caused by 63a5718. 
How to test:

1. New game and launch.
2. Press 2 to look left.
3. Press \ to go full speed.
4. Turn left until you see Atlantis well.
5. Press shift-a to manual FTL flight.
7. Keep turning left to keep Atlantis in your view. You should see an orange tint in sunrise without the commit and no tint with.
 
Assigned to @stephengtuggy, as it's his commit and I know nothing of fragment programming.


I've also noticed the following in my stdout:
```
0:26(25): error: no function with name 'textureLod'
0:26(9): error: no matching function for call to `expandPrecision(error)'; candidates are:
0:26(9): error:    float expandPrecision(vec4)
0:26(9): error: operands to arithmetic operators must be numeric
0:26(2): error: `return' with wrong type error, in function `cosAngleToDepth' returning float
Fragment Program Error: Failed to compile planet/atmo_ps2.0
Compilation of technique earth failed... trying 5_ps3.0/earth
Cause: Error compiling program vp:"planet/atmo_vs1.1.nonvar" fp:"planet/atmo_ps2.0"
Compilation of technique 5_ps3.0/earth failed... trying 4_ps2.0/earth
Cause: Error compiling program vp:"planet/atmo_vs1.1.nonvar" fp:"planet/atmo_ps2.0"
Compilation of technique 4_ps2.0/earth failed... trying 3_arbfp/earth
Cause: Error compiling program vp:"planet/atmo_vs1.1.nonvar" fp:"planet/atmo_ps2.0"
0:26(25): error: no function with name 'textureLod'
0:26(9): error: no matching function for call to `expandPrecision(error)'; candidates are:
0:26(9): error:    float expandPrecision(vec4)
0:26(9): error: operands to arithmetic operators must be numeric
0:26(2): error: `return' with wrong type error, in function `cosAngleToDepth' returning float
Fragment Program Error: Failed to compile planet/atmo_arbfp1
Compilation of technique 3_arbfp/earth failed... trying 2_ps1.4/earth
Cause: Error compiling program vp:"planet/atmo_vs1.1.nonvar" fp:"planet/atmo_arbfp1"
0:75(9): error: no matching function for call to `max(int, float)'; candidates are:
-----------------------------------------------------------------------------------------
0:75(9): error: no matching function for call to `max(int, float)'; candidates are:
0:75(9): error:    float max(float, float)
0:75(9): error:    vec2 max(vec2, float)
0:75(9): error:    vec3 max(vec3, float)
0:75(9): error:    vec4 max(vec4, float)
0:75(9): error:    vec2 max(vec2, vec2)
0:75(9): error:    vec3 max(vec3, vec3)
0:75(9): error:    vec4 max(vec4, vec4)
0:75(9): error:    int max(int, int)
0:75(9): error:    ivec2 max(ivec2, int)
0:75(9): error:    ivec3 max(ivec3, int)
0:75(9): error:    ivec4 max(ivec4, int)
0:75(9): error:    ivec2 max(ivec2, ivec2)
0:75(9): error:    ivec3 max(ivec3, ivec3)
0:75(9): error:    ivec4 max(ivec4, ivec4)
0:75(2): error: `return' with wrong type error, in function `GLOSS_power' returning float
0:197(14): warning: `mtl_gloss' used uninitialized
Fragment Program Error: Failed to compile fireglass
Compilation of technique fireglass failed... trying default
Cause: Error compiling program vp:"fireglass" fp:"fireglass"
```

The code above the line is fixed by the revert. The one below isn't.
I can't evaluate if the bottom code is indicative of some underlying issue.
i.e the commit was fine back then, but something else broke it and the code below.

**Comment by stephengtuggy** [comment]
Well, crap. Thanks for isolating the cause of the issue, @royfalk . I'll see when I can get to this.
