### PR TITLE
Fix/Bug 154

### LINKED ISSUE #154: Readme instructions obsolete & build problem
Hello,

I tried to build VS on debian 10, and ran into problems

build is broken by fb901e989ff2c1deec2c82e432adf8940e069836:
```
/usr/include/stdint.h:102:22: error: conflicting declaration ‘typedef __uintmax_t uintmax_t’
 typedef __uintmax_t  uintmax_t;
                      ^~~~~~~~~
In file included from /home/vince/dev/repo/upstream/Vega-Strike-Engine-Source/engine/src/cmd/collide2/Stdafx.h:20,
                 from /home/vince/dev/repo/upstream/Vega-Strike-Engine-Source/engine/src/cmd/collide2/Ice/Stdafx.h:1,
                 from /home/vince/dev/repo/upstream/Vega-Strike-Engine-Source/engine/src/cmd/collide2/Ice/IceAABB.cpp:21:
/home/vince/dev/repo/upstream/Vega-Strike-Engine-Source/engine/src/cmd/collide2/opcodetypes.h:178:16: note: previous declaration as ‘typedef uint64 uintmax_t’
 typedef uint64 uintmax_t;
                ^~~~~~~~~
```

With the preceding commit (672dba0a8) I could build VS:
```
mkdir build
cd build
cmake ..
make -j16
mkdir ../bin && cp vegastrike ../bin/ && cp setup/vegasettings ../bin/ && cd ..
```

but then cannot run it:
```
$ ./bin/vegasettings 
Error: Failed to find Version.txt anywhere.
vince@ryzen:~/dev/repo/upstream/Vega-Strike-Engine-Source$ ./bin/vegastrike 
Registering codec ogg.
 In path /home/vince/dev/repo/upstream/Vega-Strike-Engine-Source/bin
Vega Strike  
See http://www.gnu.org/copyleft/gpl.html for license details.

GOT SUBDIR ARG = 
Found MODDIR = /mods
USING HOMEDIR : /home/vince/.vegastrike As the home directory 
CONFIGFILE - No config found in home : /home/vince/.vegastrike/vegastrike.config
CONFIGFILE - No config found in data dir : /vegastrike.config
CONFIG FILE NOT FOUND !!!
Panic exit - no configuration
```

Am I missing something or are the README.md instructions obsolete ?

Thanks

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [ ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [x] This is a **build and** documentation change only

Issues:
- Please list any related issues
Fixes #154 

Purpose:
- What is this pull request trying to do? Fix the manual build process, as well as the instructions for performing said manual build.
- What release is this for? 0.7.x
- Is there a project or milestone we should apply this to? 0.7.x

### CODE REVIEW

File: engine/CMakeLists.txt [hunk 1]
```diff
@@ -503,7 +503,7 @@ ENDIF ()
 
 # Set the default build type to Release
 IF (NOT CMAKE_BUILD_TYPE)
-    SET(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "Release, Debug, Profiler" FORCE )
```
Comment (BenjamenMeyer) [inline engine/CMakeLists.txt:506]: We need `RelWithDebInfo` so that if someone files a bug we have some debug information to get.
Basically build types:

- Release -> RelWithDebInfo
- Debug -> Debug
- Profile -> Debug???

Comment (evertvorster) [reply engine/CMakeLists.txt:506]: I've been building the "Release" target all along, and that seems to work fine. 
Building with "Debug" also seems to work fine. 

When specifying "RelWithDebInfo" I get a compiler error, right at the start:

[  0%] Building CXX object CMakeFiles/OPcollide.dir/src/cmd/collide2/Ice/IceAABB.cpp.o
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include/stdint.h:9,
                 from /usr/include/c++/10.1.0/bits/atomic_base.h:36,
                 from /usr/include/c++/10.1.0/bits/shared_ptr_atomic.h:33,
                 from /usr/include/c++/10.1.0/memory:85,
                 from /data/OS/aur/vegastrike-engine-git/src/Vega-Strike-Engine-Source/engine/src/universe_generic.h:27,
                 from /data/OS/aur/vegastrike-engine-git/src/Vega-Strike-Engine-Source/engine/src/vs_globals.h:5,
                 from /data/OS/aur/vegastrike-engine-git/src/Vega-Strike-Engine-Source/engine/src/gfx/matrix.h:26,
                 from /data/OS/aur/vegastrike-engine-git/src/Vega-Strike-Engine-Source/engine/src/gfx/quaternion.h:5,
                 from /data/OS/aur/vegastrike-engine-git/src/Vega-Strike-Engine-Source/engine/src/cmd/collide2/opcodesysdef.h:28,
                 from /data/OS/aur/vegastrike-engine-git/src/Vega-Strike-Engine-Source/engine/src/cmd/collide2/Stdafx.h:21,
                 from /data/OS/aur/vegastrike-engine-git/src/Vega-Strike-Engine-Source/engine/src/cmd/collide2/Ice/Stdafx.h:1,
                 from /data/OS/aur/vegastrike-engine-git/src/Vega-Strike-Engine-Source/engine/src/cmd/collide2/Ice/IceAABB.cpp:21:
/usr/include/stdint.h:101:21: error: conflicting declaration 'typedef __intmax_t intmax_t'
  101 | typedef __intmax_t  intmax_t;

Comment (BenjamenMeyer) [reply engine/CMakeLists.txt:506]: I'd say that's a bug that needs fixing :)

Comment (stephengtuggy) [reply engine/CMakeLists.txt:506]: OK, I'll work on adding RelWithDebInfo back then.

Comment (BenjamenMeyer) [reply engine/CMakeLists.txt:506]: @stephengtuggy if you can repro it fine; if not, let's file an issue and we'll do a follow-up PR for it.

Comment (evertvorster) [reply engine/CMakeLists.txt:506]: This compile error is now gone.

Comment (stephengtuggy) [reply engine/CMakeLists.txt:506]: OK, I have added RelWithDebInfo back in, and changed CMake's default build configuration back to that. Do we want to change the default build configuration in vsbuild.sh as well?
